In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [12]:
class Perceptron:
    def __init__(self,eta:float=None, epochs: int=None):
        self.weights = np.random.rand(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")

In [13]:
obj = Perceptron(eta=0.01, epochs=10)

In [14]:
obj.eta

0.01

In [17]:
obj.epochs

10

In [15]:
obj.weights

array([5.12526586e-05, 1.17280879e-05, 1.01250475e-05])

In [18]:
y = np.ones((4,1))

In [19]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [20]:
X = np.ones((4,2))

In [22]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
