In [27]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [46]:
class Perceptron:
    def __init__(self,eta:float=None, epochs: int=None):
        self.weights = np.random.rand(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"Error: \n{self.error}")
                  
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch+1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
                  
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
        
        
        

In [47]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [48]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X,y

In [49]:
X,y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)

model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[5.14449044e-05 9.99220512e-05 1.50753394e-05]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[5.14449044e-05 9.99220512e-05 1.50753394e-05]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after forward pass: 
[0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[5.14449044e-05 9.99220512e-05 1.50753394e-05]
####################
--------------------
for epoch >> 4
--------------------
Predicted value after forward pass: 
[0 1 1 1]
Error: 
0    0
1    0
2

In [43]:
model_or.predict(X)

array([0, 1, 1, 1])

In [50]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [51]:
X,y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA, epochs=EPOCHS)

model_and.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[0 0 1 1]
Error: 
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-9.99117748e-02  4.19095974e-05  1.00059775e-01]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[8.82252276e-05 1.00041910e-01 5.97750186e-05]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after forward pass: 
[0 1 1 1]
Error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[-9.99117748e-02  4.19095974e-05  2.00059775e-01]
####################
--------------------
for epoch >> 4
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0
1 

In [53]:
XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [54]:
X,y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta=ETA, epochs=EPOCHS)

model_xor.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[0 1 0 1]
Error: 
0    0
1    0
2    1
3   -1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 4.51589445e-05 -9.99042669e-02  4.53501860e-05]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 1.00045159e-01  9.57331244e-05 -1.99954650e-01]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after forward pass: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 4.51589445e-05 -9.99042669e-02  4.53501860e-05]
####################
--------------------
for epoch >> 4
--------------------
Predicted value after forward pass: 
[0 0 0 0]
Error: 
0    0